name: ethiquest
description: An ethical business decision-making simulation game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.3.2
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Testing
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  build_runner: ^2.4.6
  
  # Development Tools
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  # Uncomment and add assets when we have them
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Uncomment and add fonts when we have them
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf